name: build-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: snapcore/snapcraft:edge

    steps:
      - uses: actions/checkout@v2

      - name: Install LXD
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install snapd
          sudo systemctl start snapd.service
          sudo snap install lxd
          sudo usermod --append --groups lxd $(whoami)
          sudo lxd init --auto

  #    - name: Install multipass
  #      run: |
  #        sudo snap install multipass --classic
       
  #    - name: Upgrade Snapcraft container to Bionic
  #      run: |
  #        sudo sed -i 's/xenial/bionic/g' /etc/apt/sources.list
  #        sudo apt-get -y update
  #        sudo apt-get -y dist-upgrade -o APT::Immediate-Configure=0

      - name: Download upstream epiphany snap
        run: snap download epiphany

      - name: Extract upstream epiphany snap
        run: |
          snapfile=$(ls | grep .snap)
          unsquashfs -d epiphanysnap $snapfile
          
      - name: Extract upstream epiphany snapcraft.yaml to epiphany-snapcraft
        run: cp epiphanysnap/snap/snapcraft.yaml epiphany-snapcraft

      - name: Patch epiphany-snapcraft creating snapcraft.yaml
        run: |
          sed '/      cp/d' epiphany-snapcraft >> epiphany-snapcraft-2
          grep -v '^      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/' epiphany-snapcraft-2 >> snapcraft.yaml
          
      - name: Build modified snapcraft.yaml
        run: |
          snapcraft build --use-lxd

      - name: Push .snap to Snapcraft.io
        env:
          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
        run: |
          mkdir .snapcraft
          echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
          snapcraft push --release=candidate *.snap
